language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "5.8"

before_script:
  - mysql -e 'CREATE DATABASE members;'
  - psql -c 'CREATE DATABASE members;' -U postgres

env:
  - CXX=g++-4.8 DATABASE_URL=
  - CXX=g++-4.8 DATABASE_URL=mysql://travis@localhost/members
  - CXX=g++-4.8 DATABASE_URL=postgresql://postgres@localhost/members

sudo: false

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules
